### ISSUE TITLE
Multiple instances possible, blank window and confusing behavior

### ISSUE THREAD

**Issue by michael-wenyon** [corelan/EncFSGui#10]
EncFSGui can be accidentally launched more than once simultaneously which may happen, for example, with an inexperienced user who does not notice the menubar application.

Possible consequences are a blank main window, even though the volume creation/attachment buttons still work if the volumes themselves are then accessed through the menubar item.

This is also confusing because MacOS will try and reopen previous running apps whenever the user logs in, so the 'mistake' of two instances running can survive over logout/login and restart.

Ideally there would be some way of preventing two instances of EncFSGui to run simultaneously.

behavior described in more detail [here](https://github.com/corelan/EncFSGui/issues/8)

**Comment by corelanc0d3r** [comment]
Hi,  I am currently working on building a new encfsgui version from scratch, this time using python3 / PyQT5.  
See https://github.com/corelan/pyencfsgui

The C++ version will be abandoned.
