### ISSUE TITLE
Menubar password request panel/window may be hidden (not at front)

### ISSUE THREAD

**Issue by michael-wenyon** [corelan/EncFSGui#11]
When the user's screen is filled with open windows of other apps (eg Safari), then the 'Mount' command started from the menubar item presents the password-request window *behind* open apps, where it is not visible.

It would be better if the password window could appear in front of all open apps (ie visible).

**Comment by corelanc0d3r** [comment]
Hi,  I am currently working on building a new encfsgui version from scratch, this time using python3 / PyQT5.  
See https://github.com/corelan/pyencfsgui

The C++ version will be abandoned.
