### ISSUE TITLE
'Start in MenuBar' crashes Finder at login in Mojave 10.14.1

### ISSUE THREAD

**Issue by michael-wenyon** [corelan/EncFSGui#12]
Migrated my High Sierra computer to a new Mac in Mojave 10.14.1

Settings for EncFSGui have not changed: in particular, EncFSGui set to appear in Menu Bar on login.

On Login, immediately after EncFS icon appears in Menu Bar, Menu Bar itself completely disappears and Mac is no longer running with Finder (eg desktop icons not visible). 

I can use Spotlight Search to find Finder, and launch it, thereafter Finder seems prone to crashing (disappearing) again.

Two solutions that appear to be workarounds for this:
- Unchecking option to open app on login, Finder does not crash. EncFSGui can be launched by double clicking its Applications folder icon--and menubar icon appears in Menu Bar--without crashing Finder, or:
- Adding EncFSGui to my Login Items in System Prefs, EncFSGui appears in Menu Bar (later in login sequence) and Finder **does not** crash. **Edit**: I am not sure this fix always work. For now, I am launching EncFSGui as and when I need it (first option, above): it then appears in the menu bar at the 'last' position on the left, and does not seem to cause a Finder crash when there.

**Comment by corelanc0d3r** [comment]
thank you MIchael - I'm holding off to upgrade to Mojave for a few more weeks.  It looks like perhaps there is some kind of incompatibility with the plist file that gets created when you enable the option to launch at login.

It would be great if you could confirm that, if you add encfsgui to the login items, it doesn't crash.

thanks

**Comment by michael-wenyon** [comment]
I will try to confirm this behavior: I tried on another Mac running Mojave, and it cause the same problem. 

I did once or twice see an alert/error message about a problem with the EncFSGui prefs, I think when I selected the 'open on login' checkbox (or perhaps when I deselected it, and closed Settings?). And that may have been since I moved to Mojave. But I tried repeating these steps just now and the error message did not appear.

I continue to launch EncFSGui manually and it seems OK in Mojave. I do elect to have it in the menubar (in settings), and it is at the far left of the menubar icons then.

**Comment by michael-wenyon** [comment]
So, I just had a situation where EncFSGui was launching on login, even though it was not entered as a 'Login Item' for that user, and the 'launch on login' box in Settings was not checked. It was causing Finder to crash.

I wondered if it could be MacOS trying to re-open an application (EncFSGui) that had been opened (manually, so to speak) in the previous session and was still running on logout, because relaunching is what MacOS does for ordinary applications left open on logout. However, if I actually 'quit' EncFSGui from the menubar menu before logging out, then it did _not_ start on the next login (and therefore did not make the Finder crash). This was under Mojave.

**Comment by corelanc0d3r** [comment]
Hi,  I am currently working on building a new encfsgui version from scratch, this time using python3 / PyQT5.  
See https://github.com/corelan/pyencfsgui

The C++ version will be abandoned.
