### ISSUE TITLE
crashes on macos sierra

### ISSUE THREAD

**Issue by pestolino** [corelan/EncFSGui#5]
unfortunately unstable on macos 10.12
it happens when hitting edit or when creating a new volume etc.

hopefully update soon :)
thanks!

[EncFSGui Crash macos sierra Kopie.txt](https://github.com/corelan/EncFSGui/files/493528/EncFSGui.Crash.macos.sierra.Kopie.txt)

**Comment by corelanc0d3r** [comment]
have not been able to reproduce on Sierra or High Sierra...
closing for now (but feel free to re-open if you can help me reproduce the issue)

thanks
