### ISSUE TITLE
UTF8-MAC problem

### ISSUE THREAD

**Issue by pucicu** [corelan/EncFSGui#7]
I have many files and folders that contain of umlauts. The only way to get access them is using this option in encfs:
-o modules=iconv,from_code=UTF8,to_code=UTF8-MAC

It would be nice to have such (modifiable) option also included in the GUI.

**Comment by corelanc0d3r** [comment]
I am trying to fix compilation/linking issues on High Sierra, so I'm unable to work on this right now.
For the time being, you could consider creating a little wrapper script (encfs.sh) that calls encfs and passes all options, and adds the options you need.   In EncFS, you can then try to call the wrapper script ?

**Comment by pucicu** [comment]
Hi Peter,

this might be an idea, but it seems not working. I created the sh-file encfs.sh:

#!/bin/sh

/opt/local/bin/encfs $@ -o modules=iconv,from_code=UTF8,to_code=UTF8-MAC

and used this as the encfs in the GUI. But then I get an error, that the file encfs.shctl was not found. Therefore, I created a link ln -s enfs.sh encfs.shctl. But now another error appears, stating that some parameters are missed (see attached).

Best
Norbert

**Comment by corelanc0d3r** [comment]
Hi,  I am currently working on building a new encfsgui version from scratch, this time using python3 / PyQT5.  
See https://github.com/corelan/pyencfsgui

Although I am still adding a lot of functionality, it would be great if you could already check out if the new version would support your request. (You can basically add encfs mount options for each volume)
thanks

**Comment by pucicu** [comment]
Great! At the moment, I can already mount my encrypted folders. Good work!
